// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AddressType string

const (
	AddressTypeShipping AddressType = "shipping"
	AddressTypeBilling  AddressType = "billing"
)

func (e *AddressType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AddressType(s)
	case string:
		*e = AddressType(s)
	default:
		return fmt.Errorf("unsupported scan type for AddressType: %T", src)
	}
	return nil
}

type NullAddressType struct {
	AddressType AddressType `json:"address_type"`
	Valid       bool        `json:"valid"` // Valid is true if AddressType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAddressType) Scan(value interface{}) error {
	if value == nil {
		ns.AddressType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AddressType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAddressType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AddressType), nil
}

type EntityType string

const (
	EntityTypeUser EntityType = "user"
)

func (e *EntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntityType(s)
	case string:
		*e = EntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntityType: %T", src)
	}
	return nil
}

type NullEntityType struct {
	EntityType EntityType `json:"entity_type"`
	Valid      bool       `json:"valid"` // Valid is true if EntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.EntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntityType), nil
}

type Address struct {
	ID          int32              `json:"id"`
	EntityType  EntityType         `json:"entity_type"`
	EntityID    int32              `json:"entity_id"`
	AddressType AddressType        `json:"address_type"`
	StreetLine1 string             `json:"street_line1"`
	StreetLine2 pgtype.Text        `json:"street_line2"`
	City        string             `json:"city"`
	State       string             `json:"state"`
	PostalCode  string             `json:"postal_code"`
	Country     string             `json:"country"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PasswordHash string             `json:"password_hash"`
}
